apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-hello
spec:
  replicas: 2
  selector:
    app: nginx-hello
    tier: frontend
  template:
    metadata:
      name: nginx-hello
      labels:
        app: nginx-hello
        tier: frontend
    spec:
      containers:
      - name: nginx-hello
        image: registry.ng.bluemix.net/leucir_dev/helloapp:v2
        ports:
        - containerPort: 80
