apiVersion: v1
kind: policy
metadata:
  name: worldservice-accessing-cloundant
spec:
  ingress:
  - action: allow
    protocol: tcp
    source:
      net: W.X.Y.Z/32
      ports:
      - 443
    destination: {}
  egress:
  - action: allow
    protocol: tcp
    destination:
      net: W.X.Y.Z/32
      ports:
      - 443
    source: {}
  order: 400
  selector: calico/k8s_ns == 'default' && tier == 'backend'
