apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: hello
        tier: frontend
    spec:
      containers:
      - name: hello
        image: registry.ng.bluemix.net/leucir_dev/helloapp:v2
        ports:
        - containerPort: 80
